---
title: "Explor PAHO Data: Dengue"
author: "Eugene Joh, MPH"
date: "April 8, 2018"
output: 
   html_document:
      toc: true #table of contents
      toc_float:
         collapsed: false
         smooth_scroll: true
      toc_depth: 3 #upto three depths of headings (specified by #, ## and ###)
      number_sections: false #if you want number sections at each table header
      theme: lumen #theme choices
      highlight: tango #specifies the syntax highlighting style
      code_folding: show #code folding
      df_print: paged #default print for dataframes in chunks
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)

list.of.packages <- c("sf","sp","rgdal","maptools","rgeos","raster","ggmap","leaflet","ggmap", #mapping
                      "readr","readxl", #data import
                      "lubridate","tidyr","plyr","dplyr","data.table", "forcats", #data wrangling
                      "ggplot2","scales","grid","gridExtra", #data viz
                      "viridis","RColorBrewer","ochRe", #colour palette
                      "xts","forecast","zoo", #time series
                      "R.utils","wrapr","here","devtools" #utility
                      )

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) { install.packages(new.packages) }
invisible(sapply(list.of.packages, require, character.only = T))
rm(new.packages,list.of.packages)
```

# Introduction

# Data 

## Import

## Processing

# Exploration

# Data Visualization

```{r session_info}
session_info()
```